# Site wide configuration

title: NineML
description: "A model description language for neuroscience"
logo: default-teaser.jpg
teaser: default-teaser.jpg
locale: en_US
url: http://nineml.net

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: The NineML Committee
  web: http://nineml.net/committee/
  email: nineml-users@incf.org
  twitter: nineml
  bio: ""
  avatar: site_logo.jpg


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
